# Default Config

linters:
  EmptyLineBetweenBlocks:
    enabled: false

  NestingDepth:
    enabled: false

  SelectorDepth:
    enabled: false

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: true

  StringQuotes:
    enabled: true
    style: double_quotes

  VendorPrefix:
    enabled: false
